[package]
name = "poloniex3"
version = "0.1.0"
authors = ["Sergey Potapov <blake131313@gmail.com>"]

[dependencies]
reqwest = "0.7.2"
error-chain = "*"

serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
